<?php 
 //Loader message....
 define("FIRSTNAME_INVALID","Invalid First Name");
 define("LASTNAME_INVALID","Invalid Last Name");
 define("USER_NAME_INVALID","Invalid User Name");
 define("CUSTOMER_TOKEN_INVALID","Invalid Customer token");
 define("SERVER_ERROR","Server Error");
 define("SUCCESS_WELCOME","Welcome to Home Page");
 define("IS_SUCCESS","Your request successful");
 define("IS_FAILED","Your request failed");
 define("UPDATE_SUCCESS","Updated Successfully.");
 define("LOGIN_SUCCESS","LoggedIn Successfully.");
 define("REGISTER_SUCCESS","Registered Successfully.");
 define("REGISTRATION_FAILED","Registered Failed.");
 define("OTP_SUCCESS","otp generated Successfully.");
 define("WRONG_HAPPEN","You can not tamper with the data.");
 define("EMAIL_SEND_SUCCESS","Thanks for contacting us,we will contact you soon.");
 define("MANDATORY_MISSING","Please Enter Mandatory Fields");
 define("EMAIL_INVALID","Invalid Email Format");
 define("MOBILE_INVALID","Invalid mobile no Format");
 define("DATETIME_INVALID","Invalid Date&Time Format");
 define("VEHICLETYPE_INVALID","Invalid vehicle type");
 define("CRN_INVALID","Invalid CRN no");
 define("OTP_INVALID","Invalid OTP format");
 define("EXIST_EMAIL","Email Already Exists");
 define("EXIST_MOBILE","Mobile Already Exists");
  define("REFERRAL_MOBILE_NOT_EXIST","Referral mobile does not exists");
 define("MOBILE_ALREADY_REGISTERED","Mobile Already Registered");
 define("MOBILE_NOT_REGISTERED","Mobile No Not Registered");
 define("PASSWORD_INCORRECT","Password you have entered is not correct");
 define("EXIST_VEHICLE","Vehicle Already Exists");
 define("NO_MATCH_FOUND","No match found for given mobile no");
 define("OLD_PASS_INCORRECT","Old password did not match with the existing password");
 define("PASS_MISMATCH","New password did not match with the confirm new password");
 define("COUPON_VALID","Coupon Valid !     ");
 define("COUPON_INVALID","Coupon Invalid !    ");
 define("FILE_UPLOAD_ERROR","File Could not be uploaded !!");
 define("PASSWORD_RESET_SUCCESS","Password sent to your registered mobile no");
 define("INVALID_DOC_TYPE","File Type Should Be .Docx or .Pdf or .Rtf Or .Doc");
 define("RESUME_UPLOAD_SUCCESS","Thanks for uploading your resume ! We will contact you shortly.");
 define("DRIVER_REGISTER_SUCCESS","Thank you for registering with us.We will contact you shortly");
 define("INCORRECT_OTP","You have entered incorrect OTP !!");
 define("NO_SERVICE_AREA","Sorry we do not provide service in your area !");
 define("VEHICLE_SUCCESSFULLY_REGISTERED","Vehicle succesfully registered , We will contact you soon for further verification");
 define("VIEW_IS_UP_TO_DATE","View is upto date");
 define("INVALID_JOURNEY_TYPE","Joutney type is not valid");
 define("INVALID_VEHICLE_TYPE","Vehicle type is not valid");
 define("INVALID_VEHICLE_MODE","Vehicle mode is not valid");
 define("INVALID_FARE","Fare format is not valid");
 define("NO_BOOKING","No booking record found");
 
?>