<?php 
 //Loader message....
 define("FIRSTNAME_INVALID","Invalid First Name");
 define("LASTNAME_INVALID","Invalid Last Name");
 define("USER_NAME_INVALID","Invalid User Name");
 define("SERVER_ERROR","Server Error");
 define("SUCCESS_WELCOME","Welcome to Home Page");
 define("IS_SUCCESS","Your request successful");
 define("IS_FAILED","Your request failed");
 define("LOGIN_FAILED","Username or password is incorrect !");
 define("UPDATE_SUCCESS","Updated Successfully.");
 define("LOGIN_SUCCESS","LoggedIn Successfully.");
 define("REGISTER_SUCCESS","Registered Successfully.");
 define("REGISTRATION_FAILED","Registered Failed.");
 define("WRONG_HAPPEN","You can not tamper with the data.");
 define("EMAIL_SEND_SUCCESS","Thanks for contacting us,we will contact you soon.");
 define("MANDATORY_MISSING","Please Enter Mandatory Fields");
 define("EMAIL_INVALID","Invalid Email Format");
 define("MOBILE_INVALID","Invalid mobile no Format");
 define("DATETIME_INVALID","Invalid Date&Time Format");
 define("VEHICLETYPE_INVALID","Invalid vehicle type");
 define("CRN_INVALID","Invalid CRN no");
 define("EXIST_COUPON","Coupon Already Exists");
 define("EXIST_CITY","City Already Exists");
 define("EXIST_EMAIL","Email Already Exists");
 define("EXIST_MOBILE","Mobile Already Exists");
 define("EXIST_LICENSE","License Already Exists");
 define("MOBILE_NOT_REGISTERED","Mobile No Not Registered Yet");
 define("EXIST_VEHICLE","Vehicle Already Exists");
 define("NO_MATCH_FOUND","No match found");
 define("OLD_PASS_INCORRECT","Old password did not match with the existing password");
 define("PASS_MISMATCH","New password did not match with the confirm new password");
 define("COUPON_VALID","Coupon Valid !     ");
 define("COUPON_INVALID","Coupon Invalid !    ");
 define("FILE_UPLOAD_ERROR","File Could not be uploaded !!");
 define("PASSWORD_RESET_SUCCESS","Password sent to your registered mobile no");
 define("INVALID_DOC_TYPE","File Type Should Be .Docx or .Pdf or .Rtf Or .Doc");
 define("RESUME_UPLOAD_SUCCESS","Thanks for uploading your resume ! We will contact you shortly.");
 define("DRIVER_REGISTER_SUCCESS","Thank you for registering with us.We will contact you shortly");
 define("INCORRECT_OTP","You have entered incorrect OTP !!");
 define("NO_SERVICE_AREA","Sorry we do not provide service in your area !");
 define("REFERRAL_MOBILE_NOT_EXIST","Referal mobile does not exist !");
 define("VEHICLE_SUCCESSFULLY_REGISTERED","Vehicle succesfully registered , We will contact you soon for further verification");
?>